/* BALI RANGERS — detail, aktivitas, foto & video otomatis */
(function(){
  const REPO='ipranata51-hue/sekolahku-yang-bali', BASE='dokumentasi/bali-rangers';
  const teams={
    'Tim Biopori':{id:'tim-biopori',icon:'💧',desc:'Tim yang mengembangkan dan merawat lubang biopori sebagai upaya meningkatkan resapan air, mengurangi genangan, dan mengelola bahan organik di lingkungan sekolah.',focus:'Pembuatan, pemeliharaan, pengisian bahan organik, dan pemantauan lubang biopori.'},
    'Tim Eco Enzym':{id:'tim-eco-enzym',icon:'🍃',desc:'Tim yang mengolah sisa bahan organik menjadi eco enzyme melalui proses fermentasi sehingga dapat dimanfaatkan sebagai bagian dari praktik ramah lingkungan.',focus:'Pengumpulan bahan organik, proses fermentasi, perawatan, dan dokumentasi hasil.'},
    'Tim Komposter':{id:'tim-komposter',icon:'♻️',desc:'Tim yang bertugas mengolah sampah organik sekolah menjadi kompos sebagai bagian dari upaya mengurangi sampah dan mengembalikan manfaat bahan organik ke lingkungan.',focus:'Pemilahan bahan organik, pengomposan, pemantauan proses, dan pemanfaatan kompos.'},
    'Tim Inovasi':{id:'tim-inovasi',icon:'💡',desc:'Tim penggerak gagasan dan karya kreatif yang mencari solusi sederhana, kontekstual, dan ramah lingkungan untuk mendukung Sekolahku yang BALI.',focus:'Merancang ide, membuat prototipe, menguji, memperbaiki, dan mendokumentasikan inovasi.'},
    'Tim Kampanye':{id:'tim-kampanye',icon:'📣',desc:'Tim yang mengajak seluruh warga sekolah membangun kesadaran dan kebiasaan melalui pesan, media, kegiatan, serta kampanye lingkungan yang positif.',focus:'Pesan lingkungan, poster, media edukasi, ajakan aksi, dan publikasi praktik baik.'},
    'Tim Reuse':{id:'tim-reuse',icon:'🔄',desc:'Tim yang mendorong penggunaan kembali barang atau bahan yang masih layak agar masa pakainya lebih panjang dan jumlah sampah dapat dikurangi.',focus:'Identifikasi barang yang dapat digunakan kembali dan penciptaan manfaat baru dari barang tersebut.'},
    'Tim Reduce':{id:'tim-reduce',icon:'➖',desc:'Tim yang mendorong pengurangan sampah sejak dari sumbernya melalui kebiasaan memilih, menggunakan, dan mengonsumsi secara lebih bijak.',focus:'Mengurangi plastik sekali pakai, menghemat sumber daya, dan membangun kebiasaan minim sampah.'},
    'Tim Recycle':{id:'tim-recycle',icon:'♻️',desc:'Tim yang mengolah bahan yang sudah tidak digunakan menjadi produk atau bahan baru yang memiliki nilai guna.',focus:'Pemilahan, pengolahan, pembuatan produk daur ulang, dan pameran hasil karya.'}
  };
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const gh=p=>`https://github.com/${REPO}/tree/main/${p}`;
  const api=p=>`https://api.github.com/repos/${REPO}/contents/${p}?ref=main`;
  function addCSS(){if(document.getElementById('br-style'))return;const s=document.createElement('style');s.id='br-style';s.textContent='.br-card{cursor:pointer!important;position:relative;transition:.25s!important}.br-card:hover{transform:translateY(-7px)!important;box-shadow:0 16px 32px rgba(31,63,45,.12)!important;border-color:#9bc7aa!important}.br-card:after{content:"Lihat aktivitas & dokumentasi →";display:block;margin-top:12px;color:var(--forest2);font-size:12px;font-weight:800}.br-modal{position:fixed;inset:0;z-index:100;background:rgba(8,28,18,.72);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:20px}.br-panel{width:min(980px,96vw);max-height:92vh;overflow:auto;background:var(--paper);border:1px solid var(--line);border-radius:24px;box-shadow:0 24px 70px rgba(0,0,0,.25);padding:28px}.br-close{float:right;border:0;background:#edf3ec;width:40px;height:40px;border-radius:50%;font-size:24px;cursor:pointer;color:var(--forest)}.br-title{display:flex;gap:14px;align-items:center;padding-right:50px}.br-title .ico{font-size:38px}.br-title h2{margin:0;color:var(--forest);font-size:30px}.br-lead{color:var(--muted);max-width:780px}.br-focus{padding:15px 18px;border-left:4px solid var(--gold);background:#f6f8ef;border-radius:12px;margin:18px 0;color:var(--text)}.br-actions{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.br-upload{display:inline-flex;align-items:center;gap:8px;background:var(--forest2);color:#fff!important;padding:11px 16px;border-radius:999px;font-weight:800;font-size:13px}.br-help{font-size:12px;color:var(--muted);margin:0 0 16px}.br-section-title{font-size:19px;color:var(--forest);margin:24px 0 12px}.br-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.br-media{border:1px solid var(--line);border-radius:15px;overflow:hidden;background:#f8faf5}.br-media img,.br-media video{display:block;width:100%;height:180px;object-fit:cover}.br-media figcaption{padding:9px 11px;font-size:12px;color:var(--muted);word-break:break-word}.br-empty{padding:22px;border:1px dashed #cbd8cc;border-radius:15px;color:var(--muted);background:#fbfcf9}.br-activity{padding:15px 17px;border:1px solid #dfe9dc;border-radius:15px;background:#f7faf5;margin-bottom:10px}.br-activity strong{display:block;color:var(--forest);margin-bottom:6px}.br-activity p{margin:0;color:var(--muted);white-space:pre-wrap;line-height:1.65}@media(max-width:800px){.br-gallery{grid-template-columns:repeat(2,1fr)}.br-panel{padding:20px}.br-title h2{font-size:24px}}@media(max-width:520px){.br-gallery{grid-template-columns:1fr}.br-media img,.br-media video{height:220px}}';document.head.appendChild(s)}
  async function folder(path){try{const r=await fetch(api(path));if(!r.ok)throw new Error();return await r.json()}catch(e){return null}}
  async function openTeam(team,title){const path=`${BASE}/${team.id}`,box=document.createElement('div');box.className='br-modal';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.innerHTML=`<div class="br-panel"><button class="br-close" aria-label="Tutup">×</button><div class="br-title"><div class="ico">${team.icon}</div><div><span class="badge">BALI RANGERS</span><h2>${esc(title)}</h2></div></div><p class="br-lead">${esc(team.desc)}</p><div class="br-focus"><strong>Fokus kegiatan:</strong> ${esc(team.focus)}</div><div class="br-actions"><a class="br-upload" href="${gh(path)}" target="_blank" rel="noopener">📤 Tambah Foto / Aktivitas</a></div><p class="br-help">Masuk ke folder GitHub → <b>Add file → Upload files</b>. Foto/video atau catatan aktivitas yang diunggah akan terbaca otomatis.</p><h3 class="br-section-title">📸 Dokumentasi Foto & Video</h3><div class="br-gallery"><div class="br-empty">Memuat...</div></div><h3 class="br-section-title">📝 Aktivitas Tim</h3><div class="br-activities"><div class="br-empty">Memuat...</div></div></div>`;box.addEventListener('click',e=>{if(e.target===box)box.remove()});box.querySelector('.br-close').onclick=()=>box.remove();document.body.appendChild(box);const files=await folder(path),gallery=box.querySelector('.br-gallery'),acts=box.querySelector('.br-activities');if(!Array.isArray(files)){gallery.innerHTML='<div class="br-empty">Dokumentasi belum tersedia atau belum dapat dimuat.</div>';acts.innerHTML='';return}const media=files.filter(f=>f.type==='file'&&/\.(jpe?g|png|webp|gif|mp4|webm|mov)$/i.test(f.name)),texts=files.filter(f=>f.type==='file'&&/\.(md|txt)$/i.test(f.name));gallery.innerHTML=media.length?media.map(f=>{const v=/\.(mp4|webm|mov)$/i.test(f.name);return `<figure class="br-media">${v?`<video controls preload="metadata" src="${esc(f.download_url)}"></video>`:`<img loading="lazy" src="${esc(f.download_url)}" alt="${esc(f.name)}">`}<figcaption>${esc(f.name)}</figcaption></figure>`}).join(''):'<div class="br-empty">Belum ada foto/video. Gunakan tombol Tambah Foto / Aktivitas.</div>';if(!texts.length){acts.innerHTML='<div class="br-empty">Belum ada catatan aktivitas. Unggah file <b>.txt</b> atau <b>.md</b> ke folder tim.</div>';return}const out=[];for(const f of texts.slice(0,10)){try{const t=await (await fetch(f.download_url)).text();out.push(`<div class="br-activity"><strong>${esc(f.name)}</strong><p>${esc(t)}</p></div>`)}catch(e){}}acts.innerHTML=out.length?out.join(''):'<div class="br-empty">Catatan aktivitas belum dapat dibaca.</div>'}
  function init(){addCSS();const h=[...document.querySelectorAll('h2')].find(x=>x.textContent.trim()==='BALI Rangers');if(!h)return;const section=h.closest('section');if(!section)return;section.querySelectorAll('.teams .card').forEach(card=>{const title=card.querySelector('h3')?.textContent.trim(),team=teams[title];if(!team)return;card.classList.add('br-card');card.setAttribute('tabindex','0');card.setAttribute('role','button');card.addEventListener('click',()=>openTeam(team,title));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openTeam(team,title)}})})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
