/* POPUP FIX - Sekolahku yang BALI */
(function(){
const extra={
'piket-kelas':{schedule:'Senin–Jumat',goal:'Membangun tanggung jawab, disiplin, gotong royong, dan kepedulian terhadap lingkungan belajar.',photo:'dokumentasi/piket-kelas-1.jpg'},
'piket-umum':{schedule:'Sesuai jadwal',goal:'Menumbuhkan kesadaran bahwa kebersihan sekolah merupakan tanggung jawab bersama.',photo:'dokumentasi/piket-umum.jpg'},
'operasi-semut':{schedule:'Senin–Jumat',goal:'Membangun kepedulian dan kebiasaan menjaga kebersihan secara spontan.',photo:'dokumentasi/operasi-semut.jpg'},
'general-clean-up':{schedule:'Setiap Jumat secara bergiliran',goal:'Menjaga lingkungan sekolah tetap bersih, nyaman, sehat, dan tertata.',photo:'dokumentasi/general-clean-up.jpg'},
'sisir-meja':{schedule:'Setiap hari',goal:'Membentuk kebiasaan menjaga kebersihan sebelum meninggalkan tempat.',photo:'dokumentasi/sisir-meja.jpg'},
'pemilahan-sampah':{schedule:'Setiap hari',goal:'Membangun kepedulian terhadap pengelolaan sampah.',photo:'dokumentasi/pemilahan-sampah.jpg'},
'perawatan-tanaman':{schedule:'Setiap hari',goal:'Menumbuhkan tanggung jawab, kesabaran, dan kecintaan terhadap lingkungan.',photo:'dokumentasi/perawatan-tanaman.jpg'},
'piral':{schedule:'Sesuai pelaksanaan program',goal:'Memanfaatkan kertas dan menumbuhkan kreativitas serta kepedulian lingkungan.'},
'si-pahala':{schedule:'Sesuai kondisi dan kebutuhan',goal:'Memanfaatkan air hujan dan menumbuhkan kesadaran terhadap konservasi air.',photo:'si-pahala.jpeg'},
'a-patar':{schedule:'Sesuai pelaksanaan program',goal:'Membiasakan penggunaan tumbler dan mengurangi penggunaan botol plastik sekali pakai.'},
'dupa':{schedule:'Sesuai kebutuhan',goal:'Menjaga kebersihan dan ketertiban lingkungan sekolah.'},
'eco-enzym':{schedule:'Sesuai pelaksanaan program',goal:'Memanfaatkan bahan organik dan mendorong praktik ramah lingkungan.'},
'komposting':{schedule:'Sesuai pelaksanaan program',goal:'Mengolah sampah organik menjadi media yang bermanfaat dan mengurangi sampah.'},
'ecobrick':{schedule:'Sesuai pelaksanaan program',goal:'Memanfaatkan sampah plastik agar memiliki nilai guna kembali.'},
'recycle':{schedule:'Sesuai pelaksanaan program',goal:'Mengolah bahan yang tidak terpakai menjadi produk baru yang bermanfaat.'},
'lagu-bali':{schedule:'Sesuai kegiatan sekolah',goal:'Menanamkan semangat Bersih, Asri, Lestari, dan Indah melalui media musik.',audio:'lagu-sekolahku-yang-bali.mp3'},
'papan-nama-tanaman-digital':{schedule:'Sesuai pelaksanaan program',goal:'Mengenalkan jenis dan identitas tanaman di lingkungan sekolah, menjadikan lingkungan sebagai sumber belajar kontekstual, serta memanfaatkan teknologi untuk mendukung edukasi lingkungan.'}
};
function closePopup(){const m=document.querySelector('[data-popup-fix="true"]');if(m)m.remove();document.body.classList.remove('aksi-modal-open')}
function openPopup(id){const card=document.querySelector('[data-popup-id="'+CSS.escape(id)+'"]');if(!card)return;closePopup();const icon=(card.querySelector('.aksi-icon')?.textContent||'🌿').trim(),type=(card.querySelector('.aksi-label')?.textContent||'PROGRAM').trim(),title=(card.querySelector('h3')?.textContent||id).trim(),desc=(card.querySelector('p')?.textContent||'').trim(),d=extra[id]||{};const box=document.createElement('div');box.className='aksi-modal';box.dataset.popupFix='true';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.innerHTML=`<div class="aksi-modal-panel"><button class="aksi-modal-close" type="button" aria-label="Tutup detail">×</button>${d.photo?`<img class="aksi-modal-photo" src="${d.photo}" alt="Dokumentasi ${title}">`:`<div class="aksi-modal-icon">${icon}</div>`}<span class="aksi-modal-type">${type}</span><h2>${title}</h2><p>${desc}</p>${d.audio&&id==='lagu-bali'?`<div class="aksi-audio-box"><strong>🎵 Dengarkan Lagu Sekolahku yang BALI</strong><audio controls preload="metadata" playsinline src="${d.audio}" style="width:100%;margin-top:12px"></audio></div>`:''}<div class="aksi-detail-grid"><div class="aksi-detail-box"><strong>🎯 Tujuan</strong><span>${d.goal||(type==='PEMBIASAAN'?'Membangun budaya peduli lingkungan melalui kebiasaan yang dilakukan secara konsisten.':'Mewujudkan solusi kreatif untuk mendukung lingkungan sekolah yang Bersih, Asri, Lestari, dan Indah.')}</span></div><div class="aksi-detail-box"><strong>📅 Pelaksanaan</strong><span>${d.schedule||'Sesuai pelaksanaan program'}</span></div></div><div class="aksi-modal-note">🌿 <b>Sekolahku yang BALI</b> — Bersih • Asri • Lestari • Indah</div></div>`;box.addEventListener('click',e=>{if(e.target===box)closePopup()});box.querySelector('.aksi-modal-close').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();closePopup()});document.body.appendChild(box);document.body.classList.add('aksi-modal-open');box.querySelector('.aksi-modal-close').focus()}
function wireCards(){document.querySelectorAll('.aksi-card').forEach(card=>{const attr=card.getAttribute('onclick')||'',m=attr.match(/openAksi\(['"]([^'"]+)['"]\)/),id=card.dataset.popupId||m?.[1];if(!id)return;card.dataset.popupId=id;card.removeAttribute('onclick');if(card.dataset.popupWired==='1')return;card.dataset.popupWired='1';card.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openPopup(id)},true);const btn=card.querySelector('button');if(btn){btn.type='button';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openPopup(id)},true)}});addPapanNamaCard()}
function addPapanNamaCard(){if(document.querySelector('[data-popup-id="papan-nama-tanaman-digital"]'))return;const grids=[...document.querySelectorAll('.aksi-grid')];if(!grids.length)return;const grid=grids.find(g=>g.querySelector('.aksi-card.inovasi'))||grids[grids.length-1];const card=document.createElement('article');card.className='aksi-card inovasi';card.dataset.popupId='papan-nama-tanaman-digital';card.innerHTML='<div class="aksi-icon">🌿</div><div class="aksi-label">INOVASI</div><h3>Papan Nama Tanaman Digital</h3><p>Media informasi tanaman yang menggabungkan identitas tanaman, pembelajaran lingkungan, dan teknologi digital.</p><button type="button">Lihat Detail →</button>';grid.appendChild(card);wireCards()}
function dedupeSapa(){const nav=[...document.querySelectorAll('nav a,.links a')].filter(a=>/sapa\s*bali/i.test(a.textContent||''));nav.slice(1).forEach(a=>a.remove());const sections=[...document.querySelectorAll('section')].filter(s=>s.id==='sapa-bali'||/sapa\s*bali/i.test(s.textContent||''));sections.slice(1).forEach(s=>s.remove())}
function boot(){dedupeSapa();wireCards();[500,1500,3000].forEach(t=>setTimeout(()=>{dedupeSapa();wireCards()},t))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.openAksi=openPopup;window.closeAksi=closePopup;
function setupPublicSapa(){const replaceForm=()=>{const form=document.getElementById('sapaForm');if(!form||form.dataset.publicSapa==='1')return;const clone=form.cloneNode(true);clone.dataset.publicSapa='1';const honeypot=document.createElement('input');honeypot.type='text';honeypot.name='website';honeypot.autocomplete='off';honeypot.tabIndex=-1;honeypot.style.cssText='position:absolute;left:-9999px;height:1px;width:1px;opacity:0';clone.appendChild(honeypot);form.replaceWith(clone);const note=clone.parentElement?.querySelector('.sapa-note');if(note)note.innerHTML='SAPA BALI akan melalui <strong>moderasi pengelola sekolah</strong> sebelum ditampilkan pada website. Pengunjung dapat mengirim tanpa akun GitHub.';clone.addEventListener('submit',async e=>{e.preventDefault();const submit=clone.querySelector('.sapa-submit'),nama=clone.querySelector('#sapaNama')?.value.trim()||'',status=clone.querySelector('#sapaStatus')?.value||'',pesan=clone.querySelector('#sapaPesan')?.value.trim()||'',website=clone.querySelector('[name="website"]')?.value||'';if(!nama||!pesan){alert('Mohon lengkapi nama dan saran/pandangan.');return}if(nama.length>80||pesan.length>3000){alert('Mohon periksa panjang nama atau pesan.');return}if(submit){submit.disabled=true;submit.textContent='⏳ Mengirim...'}try{const r=await fetch('/api/sapa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nama,status,pesan,website})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Pengiriman gagal');clone.reset();alert('Terima kasih! SAPA BALI sudah diterima dan akan ditinjau oleh pengelola sekolah.')}catch(err){alert('SAPA BALI belum terkirim. Silakan coba lagi.')}finally{if(submit){submit.disabled=false;submit.textContent='🌱 Kirim SAPA BALI'}}})};if(document.getElementById('sapaForm'))replaceForm();const obs=new MutationObserver(()=>{dedupeSapa();if(document.getElementById('sapaForm'))replaceForm()});obs.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupPublicSapa);else setupPublicSapa();
})();
