/* SEKOLAHKU YANG BALI — UI TERPADU
   Satu modul untuk popup detail + Papan Nama Tanaman Digital + dokumentasi.
*/
(function(){
  const REPO='ipranata51-hue/sekolahku-yang-bali';
  const root='dokumentasi';
  const extra={
    'piral':{goal:'Memanfaatkan kertas bekas menjadi PIRAL (Piala Ramah Lingkungan) dan menumbuhkan kreativitas serta kepedulian lingkungan.'},
    'si-pahala':{goal:'Memanfaatkan air hujan dan menumbuhkan kesadaran terhadap konservasi air.'},
    'a-patar':{goal:'Membiasakan penggunaan tumbler dan mengurangi penggunaan botol plastik sekali pakai.'},
    'dupa':{goal:'Mengembangkan praktik pengelolaan lingkungan yang bersih dan tertib dalam kegiatan sekolah.'},
    'eco-enzym':{goal:'Memanfaatkan bahan organik menjadi produk yang berguna serta mengurangi sampah.'},
    'komposting':{goal:'Mengolah sampah organik menjadi media yang bermanfaat dan mengurangi sampah.'},
    'ecobrick':{goal:'Memanfaatkan sampah plastik agar memiliki nilai guna kembali.'},
    'recycle':{goal:'Mengolah bahan yang tidak terpakai menjadi produk baru yang bermanfaat.'},
    'lagu-bali':{goal:'Menanamkan semangat Bersih, Asri, Lestari, dan Indah melalui media musik.',audio:'lagu-sekolahku-yang-bali.mp3'},
    'papan-nama-tanaman-digital':{goal:'Mengenalkan jenis dan identitas tanaman di lingkungan sekolah, menjadikan lingkungan sebagai sumber belajar kontekstual, serta memanfaatkan teknologi untuk mendukung edukasi lingkungan.'}
  };
  const gh=p=>`https://github.com/${REPO}/tree/main/${p}`;
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function style(){if(document.getElementById('site-ui-style'))return;const s=document.createElement('style');s.id='site-ui-style';s.textContent=`
  body.ui-lock{overflow:hidden}.ui-modal{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(7,24,15,.72);backdrop-filter:blur(7px)}.ui-panel{position:relative;width:min(760px,96vw);max-height:90vh;overflow:auto;background:#fffdf8;border-radius:26px;padding:30px;box-shadow:0 25px 80px rgba(0,0,0,.3);border:1px solid #dce8dc}.ui-close{position:absolute;right:16px;top:16px;width:40px;height:40px;border:0;border-radius:50%;background:#edf3eb;color:#234a31;font-size:25px;cursor:pointer}.ui-panel h2{color:#183b28;margin:12px 45px 10px 0;font-size:32px}.ui-panel p{color:#5f6d61;line-height:1.65}.ui-type{display:inline-block;padding:6px 11px;border-radius:999px;background:#e6f1e5;color:#2f6b46;font-size:11px;font-weight:900}.ui-box{margin-top:18px;padding:17px;border-radius:17px;background:#f3f8f1;border:1px solid #dce8dc}.ui-box strong{display:block;color:#214d32;margin-bottom:7px}.ui-audio{margin-top:18px;padding:17px;border-radius:17px;background:#f5f0df}.ui-audio audio{width:100%;margin-top:10px}.ui-doc{margin-top:25px;padding-top:22px;border-top:1px solid #e0e7dc}.ui-doc h3{color:#214d32}.ui-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.ui-btn{display:inline-flex;align-items:center;justify-content:center;padding:11px 17px;border-radius:999px;text-decoration:none;font-weight:800;font-size:13px}.ui-primary{background:#2f6b46;color:white!important}.ui-secondary{background:#e9f1e8;color:#214d32!important}.ui-upload{margin-top:28px;padding:25px;border-radius:24px;background:linear-gradient(135deg,#f0f8f0,#fffdf6);border:1px solid #d9e7d9}.ui-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.ui-upload-card{padding:22px;background:#fff;border:1px solid #dfe8dc;border-radius:19px}.ui-upload-card h3{margin:7px 0;color:#214d32}.ui-upload-card p{font-size:13px}.ui-upload-card .ui-actions{margin-top:12px}@media(max-width:700px){.ui-upload-grid{grid-template-columns:1fr}.ui-panel{padding:22px}.ui-panel h2{font-size:26px}}
  `;document.head.appendChild(s)}
  function close(){document.querySelectorAll('.ui-modal').forEach(x=>x.remove());document.body.classList.remove('ui-lock')}
  function open(id,card){close();const title=card?.querySelector('h3')?.textContent?.trim()||id;const type=card?.querySelector('.aksi-label')?.textContent?.trim()||'INOVASI';const desc=card?.querySelector('p')?.textContent?.trim()||'';const d=extra[id]||{};const box=document.createElement('div');box.className='ui-modal';box.innerHTML=`<div class="ui-panel" role="dialog" aria-modal="true"><button class="ui-close" type="button">×</button><span class="ui-type">${esc(type)}</span><h2>${esc(title)}</h2><p>${esc(desc)}</p>${d.audio?`<div class="ui-audio"><strong>🎵 Dengarkan Lagu Sekolahku yang BALI</strong><audio controls preload="metadata" src="${d.audio}"></audio></div>`:''}<div class="ui-box"><strong>🎯 Tujuan</strong><span>${esc(d.goal||(type==='PEMBIASAAN'?'Membangun budaya peduli lingkungan melalui kebiasaan yang dilakukan secara konsisten.':'Mewujudkan solusi kreatif untuk mendukung lingkungan sekolah yang Bersih, Asri, Lestari, dan Indah.'))}</span></div><div class="ui-box"><strong>📅 Pelaksanaan</strong><span>Sesuai pelaksanaan program</span></div><div class="ui-doc"><h3>📸 Dokumentasi</h3><p>Dokumentasi kegiatan dikelola oleh admin sekolah dan dapat ditambahkan tanpa mengubah HTML.</p><div class="ui-actions"><a class="ui-btn ui-primary" href="${gh(root+'/'+(id==='papan-nama-tanaman-digital'?'inovasi':'inovasi'))}" target="_blank" rel="noopener">📤 Area Dokumentasi</a></div></div></div>`;box.addEventListener('click',e=>{if(e.target===box)close()});box.querySelector('.ui-close').onclick=close;document.body.appendChild(box);document.body.classList.add('ui-lock');box.querySelector('.ui-close').focus()}
  function wire(){document.querySelectorAll('.aksi-card').forEach(card=>{let id=card.dataset.uiId;const raw=card.getAttribute('onclick')||'';const m=raw.match(/openAksi\(['"]([^'"]+)['"]\)/);id=id||m?.[1];if(!id)return;card.dataset.uiId=id;card.removeAttribute('onclick');if(card.dataset.uiWired)return;card.dataset.uiWired='1';card.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(id,card)});});addPapan()}
  function addPapan(){if(document.querySelector('[data-ui-id="papan-nama-tanaman-digital"]'))return;const grid=[...document.querySelectorAll('.aksi-grid')].find(g=>g.querySelector('.aksi-card.inovasi'));if(!grid)return;const c=document.createElement('article');c.className='aksi-card inovasi';c.dataset.uiId='papan-nama-tanaman-digital';c.innerHTML='<div class="aksi-icon">🌿</div><span class="aksi-label">INOVASI</span><h3>Papan Nama Tanaman Digital</h3><p>Media informasi tanaman yang menggabungkan identitas tanaman, pembelajaran lingkungan, dan teknologi digital.</p><button type="button">Lihat Detail →</button>';grid.appendChild(c);wire()}
  function uploadSection(){if(document.getElementById('ui-upload-section'))return;const aksi=document.getElementById('aksi');if(!aksi)return;const sec=document.createElement('section');sec.id='ui-upload-section';sec.className='section';sec.innerHTML=`<div class="c"><div class="head"><span class="kicker">Dokumentasi</span><h2>Kelola Dokumentasi</h2><p class="muted">Area ini disiapkan untuk admin sekolah. Pengunjung umum tidak mendapatkan akses upload.</p></div><div class="ui-upload"><div class="ui-upload-grid"><article class="ui-upload-card"><div style="font-size:36px">🌱</div><span class="badge">PEMBIASAAN</span><h3>Dokumentasi Pembiasaan</h3><p>Foto dan video kegiatan pembiasaan sekolah.</p><div class="ui-actions"><a class="ui-btn ui-primary" href="${gh(root+'/pembiasaan')}" target="_blank" rel="noopener">📤 Upload Foto</a></div></article><article class="ui-upload-card"><div style="font-size:36px">💡</div><span class="badge">INOVASI</span><h3>Dokumentasi Inovasi</h3><p>Foto dan video produk serta kegiatan inovasi.</p><div class="ui-actions"><a class="ui-btn ui-primary" href="${gh(root+'/inovasi')}" target="_blank" rel="noopener">📤 Upload Foto</a></div></article></div></div></div>`;aksi.insertAdjacentElement('afterend',sec)}
  function boot(){style();wire();uploadSection();setTimeout(wire,700);setTimeout(wire,1800)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
